-- 시퀀스
CREATE SEQUENCE SEQ_ATTACH_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BRAND_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CART_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CATEGORY_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COMMENT_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DESIGNIMAGE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INQUIRY_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_OPT_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POINT_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROD_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REVIEW_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STOCK_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SUSP_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRASH_NO START WITH 1 INCREMENT BY 1;

-- TBL_AUTHORITY
INSERT INTO TBL_AUTHORITY VALUES (1, 'ROLE_MEMBER', '일반회원');
INSERT INTO TBL_AUTHORITY VALUES (2, 'ROLE_ADMIN', '관리자');
-- 관리자
INSERT INTO TBL_ROLE VALUES('admin01', 2);

-- TBL_BRAND
INSERT INTO TBL_BRAND VALUES (1, '글입다');

-- TBL_CATEGORY
INSERT INTO TBL_CATEGORY VALUES (1, '153프리미엄', '프리미엄펜');

-- TBL_INQUIRY DUMMY DATA 생성
--BEGIN
--FOR i IN 1..100 LOOP
--INSERT INTO TBL_INQUIRY(INQUIRY_NO, MEMBER_ID, INQUIRY_TITLE, INQUIRY_CONTENT, INQUIRY_TYPE, INQUIRY_REG_DATE, INQUIRY_ANSWERED_YN)
--VALUES(SEQ_INQUIRY_NO.NEXTVAL, (SELECT A.MEMBER_ID FROM (SELECT MEMBER_ID FROM TBL_MEMBER ORDER BY DBMS_RANDOM.RANDOM) A WHERE ROWNUM <= 1 AND A.MEMBER_ID <> 'admin01'), '테스트 제목입니다 ' || i, '<p>테스트 내용입니다</p>', '배송', TO_DATE('2023-08-01', 'YYYY-MM-DD'), 'N');
--END LOOP;
--END;