# server port config
server:
  port: 8001

# datasource config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##GBMALL
    password: GBMALL
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml

# logging level
logging:
  level:
    '[com.reminder.geulbeot]': debug
